---
title: "p8105_hw2_xw3106"
output: html_document
---

```{r}
#import library
library(tidyverse)
library(readxl)
```

#Problem 1
```{r}
#read files
pols <- read_csv("fivethirtyeight_datasets/pols-month.csv")
snp <- read_csv("fivethirtyeight_datasets/snp.csv")
unemployment <- read_csv("fivethirtyeight_datasets/unemployment.csv")

#clean data in pols-month.csv
pols_clean <- pols |>
  janitor::clean_names() |>
  separate(mon, c("year", "month", "day"),convert= TRUE) |>
  mutate(month = factor(month.name[month],levels = month.name),
         president = if_else(prez_gop == 1, "gop", "dem")) |>
  select(year, month, president, everything(),-prez_gop, -prez_dem, -day)|>
  arrange(year, month)

#clean data in snp.csv
snp_clean <- snp |>
  janitor::clean_names() |>
  separate(date, c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(month = factor(month.name[month],levels = month.name),
         year = if_else(year <= 30, year + 2000, year + 1900)) |>
  select(year, month, everything(), -day)|>
  arrange(year, month)

#clean data in unemployment.csv
unemp_clean <- unemployment |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to  = "month",
    values_to = "unemployment") |>
  mutate(
    month = factor(month, levels = tolower(month.abb), labels = month.name))|>
  arrange(year, month)

#merge data sets
df = left_join(pols_clean, snp_clean, by = c("year", "month")) |>
  left_join(unemp_clean, by = c("year", "month"))
```

#Problem 2
```{r}
#read Mr. Trash Wheel sheet
mr_trash_df = read_excel("202409 Trash Wheel Collection Data.xlsx",
                sheet = "Mr. Trash Wheel",
                range = "A2:M655")|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))|>
  mutate(sports_balls = as.integer(round(sports_balls)),
         year = as.integer(year),
         wheel = "Mr. Trash Wheel",
         day = lubridate::day(date))|>
  select(wheel,dumpster,year,month,day,everything(),-date)

#read Professor Trash Wheel 
professor_trash_df = read_excel("202409 Trash Wheel Collection Data.xlsx",
                sheet = "Professor Trash Wheel",
                range = "A2:L125")|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))|>
  mutate(wheel = "Professor Trash Wheel",
         year = as.integer(year),
         day = lubridate::day(date))|>
  select(wheel,dumpster,year,month,day,everything(),-date)

#read Gwynnda Trash Wheel 
gwynnda_trash_df = read_excel("202409 Trash Wheel Collection Data.xlsx",
                sheet = "Gwynnda Trash Wheel",
                range = "A2:K266")|>
  janitor::clean_names()|>
  filter(!is.na(dumpster))|>
  mutate(wheel = "Gwynnda Wheel",
         year = as.integer(year),
         day = lubridate::day(date))|>
  select(wheel,dumpster,year,month,day,everything(),-date)

#bind rows
trashwheel_df = bind_rows(mr_trash_df, professor_trash_df, gwynnda_trash_df)
```

